language: scala

sudo: false

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

script:
  - sbt scripted
  - cd example && sbt run

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

